name: budgetbuddy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.0  # Updated to latest version
  sqflite_common: ^2.5.4+5  # Updated to latest version
  path: ^1.9.0  # Updated to latest version
  file_picker: ^8.1.3
  csv: ^6.0.0
  excel: ^4.0.6  # Updated to latest version
  idb_shim: ^2.6.1+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Updated to latest version

flutter:
  uses-material-design: true

  assets:
    - assets/accounttypes.json
