name: Flutter Windows CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        flutter-version: [3.13.0] # Specify the Flutter version you're using

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}

      - name: Install dependencies
        run: flutter pub get

      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop

      - name: Build Windows release
        run: flutter build windows --release

      - name: Upload build artifacts (Windows executable)
        uses: actions/upload-artifact@v3
        with:
          name: windows-release
          path: build/windows/runner/Release/
