name: CI Pipeline for Windows

on:
  push:
    branches:
      - main
      - feature/unittests
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test

      - name: Build Windows App
        run: flutter build windows

      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/runner/Release/
